name: taverns
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.0
  intl: ^0.18.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  sqflite: ^2.3.0
  fpdart: ^1.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  another_flushbar: ^1.12.30
  toggle_switch: ^2.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Circular Std
      fonts: 
        - asset: assets/fonts/CircularStdBold.ttf
          weight: 700
        - asset: assets/fonts/CircularStdMedium.ttf
          weight: 500
        - asset: assets/fonts/CircularStdBook.ttf
          weight: 500
    - family: Cairo
      fonts: 
        - asset: assets/fonts/CairoRegular.ttf
          weight: 400
        - asset: assets/fonts/CairoBold.ttf
          weight: 700
        - asset: assets/fonts/CairoSemiBold.ttf
          weight: 600
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MulishRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MulishRomanRegular.ttf
          weight: 400
    - family: Product Sans
      fonts: 
        - asset: assets/fonts/ProductSansBold.ttf
          weight: 700
    - family: SF Pro
      fonts: 
        - asset: assets/fonts/SFProRegular.ttf
          weight: 400
